---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Format data disk
      community.general.filesystem:
       fstype: ext4
       dev: /dev/disk/by-id/google-persistent-disk-1

    - name: Mount data disk
      ansible.posix.mount:
       path: /var/www
       src: /dev/disk/by-id/google-persistent-disk-1
       fstype: ext4
       state: mounted

    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip
          - python3-venv
          - tree
          - apache2
          - php
          - php-xml
          - curl    
          
    - name: Run script to install Cloud Logging
      ansible.builtin.shell: |
        curl -sSO https://dl.google.com/cloudagents/add-logging-agent-repo.sh
        sudo bash add-logging-agent-repo.sh --also-install
              
    - name: Download and extract dokuwiki-stable.tgz
      ansible.builtin.unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        extra_opts: --strip-components=1
        owner: www-data
        group: www-data
        remote_src: yes 

    - name: Create backup shell script
      copy: 
        dest: /etc/cron.hourly/backup
        content: |
          #!/bin/bash
          TARGET="gs://project-dokuwiki-backup"
          tar_file=/tmp/dokuwiki-backup-$(date +%s).tar.gz
          tar -czf $tar_file /var/www/html 2>/dev/null 
          gsutil cp $tar_file $TARGET
          rm -f $tar_file

    - name: Make backup script executable
      ansible.builtin.file:
        path: /etc/cron.hourly/backup
        mode: u+x

    - name: Deny Directory Access in apache2
      ansible.builtin.blockinfile:
        path: /etc/apache2/sites-available/000-default.conf
        insertafter: "</VirtualHost>"
        block: |
          <LocationMatch "/(data|conf|bin|inc|vendor)/">
              Order allow,deny
              Deny from all
              Satisfy All
          </LocationMatch>
    - name: Reload apache2 for changes to take effect
      ansible.builtin.shell: |
        sudo /etc/init.d/apache2 reload

        
      