---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip
          - python3-venv
          - tree
          - apache2
          - php
          - php-xml          
    
    - name: Format data disk
      community.general.filesystem:
       fstype: ext4
       dev: /dev/disk/by-id/google-persistent-disk-1

    - name: Mount data disk
      ansible.posix.mount:
       path: /data
       src: /dev/disk/by-id/google-persistent-disk-1
       fstype: ext4
       state: mounted

    - name: Download and extract dokuwiki-stable.tgz
      ansible.builtin.unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        remote_src: yes 