---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - nodejs

    - name: add nodeuser
      ansible.builtin.user:
        name: nodeuser
        system: yes
    
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/melvin3030/cis-91.git'
        dest: /home/nodeuser/checkout

    - name: change file ownership
      ansible.builtin.file:
        path: /home/nodeuser/checkout/hello-nodejs/app.js
        owner: nodeuser
        group: nodeuser
        mode: '0640'

    - name: add node_app.service file
      ansible.builtin.copy:
        src: ~/cis-91/lab12/node_app.service
        dest: /lib/systemd/system/node_app.service

    - name: Start nodejs service
      ansible.builtin.systemd:
        daemon_reload: yes
        name: node_app.service
        enabled: yes

    - name: Reboot machine
      reboot: